### ISSUE TITLE
DGL_GCN-Transformer cannot work.

### ISSUE THREAD

**Issue by zpking** [kexinhuang12345/DeepPurpose#161]
Traceback (most recent call last):
  File "/root/prog/wzp/DeepPurpose/MyWork/test.py", line 51, in <module>
    model.train(train, val, max_auc = 0.8, max_auprc = 0.8)
  File "/root/prog/wzp/DeepPurpose/DeepPurpose/DTI.py", line 445, in train
    score = self.model(v_d, v_p)
  File "/root/anaconda3/envs/DeepPurpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/prog/wzp/DeepPurpose/DeepPurpose/DTI.py", line 54, in forward
    v_f = torch.cat((v_D, v_P), 1)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 2 and 64

Hello, I am very interested in your job and this combination cannot work.

**Comment by kexinhuang12345** [comment]
Is other combination works? Could you share reproduce code?
