### ISSUE TITLE
ModuleNotFoundError: No module named 'descriptastorus'

### ISSUE THREAD

**Issue by reni8911** [kexinhuang12345/DeepPurpose#178]
**I installed the environment through environment.yml, and after successful installation, I ran Drug Properties Prediction with an error message as follows:**

> Traceback (most recent call last):
>   File "/mnt/sdb1/yinxiaoru/AIDD/project/ADMET/project/DeepPurpose-master/DeepPurpose/utils.py", line 15, in <module>
>     from descriptastorus.descriptors import rdDescriptors, rdNormalizedDescriptors
> ModuleNotFoundError: No module named 'descriptastorus'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "run_admet.py", line 4, in <module>
>     from DeepPurpose import CompoundPred as models
>   File "/mnt/sdb1/yinxiaoru/AIDD/project/ADMET/project/DeepPurpose-master/DeepPurpose/CompoundPred.py", line 24, in <module>
>     from DeepPurpose.utils import 
>   File "/mnt/sdb1/yinxiaoru/AIDD/project/ADMET/project/DeepPurpose-master/DeepPurpose/utils.py", line 17, in <module>
>     raise ImportError("Please install pip install git+https://github.com/bp-kelley/descriptastorus and pip install pandas-flavor")
> ImportError: Please install pip install git+https://github.com/bp-kelley/descriptastorus and pip install pandas-flavor

**Prompt for installing descriptastrorus and pandas flavor. An error occurred while installing descriptastrorus, with the following error message:**

`pip install git+https://github.com/bp-kelley/descriptastorus`

> Looking in indexes: http://pypi.douban.com/simple/, https://pypi.ngc.nvidia.com
> Collecting git+https://github.com/bp-kelley/descriptastorus
>   Cloning https://github.com/bp-kelley/descriptastorus to /mnt/sdb1/yinxiaoru/.temp_dir/pip-req-build-q1ez9ilq
>   Running command git clone --filter=blob:none --quiet https://github.com/bp-kelley/descriptastorus /mnt/sdb1/yinxiaoru/.temp_dir/pip-req-build-q1ez9ilq
>   fatal: unable to access 'https://github.com/bp-kelley/descriptastorus/': Empty reply from server
>   warning: Clone succeeded, but checkout failed.
>   You can inspect what was checked out with 'git status'
>   and retry the checkout with 'git checkout -f HEAD'
> 
>   error: subprocess-exited-with-error
> 
>   × git clone --filter=blob:none --quiet https://github.com/bp-kelley/descriptastorus /mnt/sdb1/yinxiaoru/.temp_dir/pip-req-build-q1ez9ilq did not run successfully.
>   │ exit code: 128
>   ╰─> See above for output.
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × git clone --filter=blob:none --quiet https://github.com/bp-kelley/descriptastorus /mnt/sdb1/yinxiaoru/.temp_dir/pip-req-build-q1ez9ilq did not run successfully.
> │ exit code: 128
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jiaqingxie** [comment]
Have you directly tried pip install git+https://github.com/bp-kelley/descriptastorus.  Otherwise, I think you could try dufferent python env (python 3.10 / python 3.9) to solve this problem.
